#!/bin/bash

echo "Building docker image for $1"
echo "#==============================================================================#"
docker images | awk '{print $3}'  | xargs docker rmi -f
echo "#==============================================================================#"
docker build . -t your_project_container:$1 --progress plain --file Dockerfile.$1
echo "#==============================================================================#"
docker run --rm -p 8080:8080 docker.io/library/your_project_container:$1
echo "#==============================================================================#"
